"""Add permission category and seed version tracking

Revision ID: 658e7ec85871
Revises: 1f1ffa26309b
Create Date: 2026-06-20 21:08:44.290597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658e7ec85871'
down_revision: Union[str, Sequence[str], None] = '1f1ffa26309b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_versions_version'), 'seed_versions', ['version'], unique=True)
    op.add_column('permissions', sa.Column('category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'category')
    op.drop_index(op.f('ix_seed_versions_version'), table_name='seed_versions')
    op.drop_table('seed_versions')
    # ### end Alembic commands ###
